version: '3.8'

services:
  nft-spigot:
    image: itzg/minecraft-server:java21-alpine
    container_name: nft-spigot
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.21.1"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "minecraft123"
      MEMORY: "5G"
    volumes:
      - ./docker/spigot-data:/data
    restart: unless-stopped
    networks:
      - blockchain_network

  hardhat:
    build:
      context: ./contracts
    container_name: hardhat-node
    volumes:
      - ./contracts:/source:ro
      - ./docker/hardhat:/app
    ports:
      - "8545:8545"
    restart: unless-stopped
    networks:
      - blockchain_network

  front:
    build:
      context: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/source:ro
      - ./docker/frontend:/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    restart: unless-stopped
    networks:
      - blockchain_network

#  minecraft_plugin:
#    build:
#      context: ./minecraft
#      dockerfile: Dockerfile
#    container_name: minecraft-plugin-builder
#    volumes:
#      - ./minecraft:/app
#      - target_minecraft:/app/target
#    working_dir: /app
#    command: ["mvn", "clean", "package"]
#    restart: "no"
#    networks:
#      - blockchain_network



volumes:
  hardhat_data: {} # Stockage des fichiers de Hardhat
  frontend_build: {} # Cache de build Next.js
  target_minecraft: {} # Build du plugin Java
  node_modules_contracts: {} # node_modules de Hardhat
  node_modules_frontend: {} # node_modules du frontend

networks:
  blockchain_network:
