name: marketplace-nft
version: '1.0.0'
main: fr.sayoden.nft.MarketPlacePlugin
api-version: '1.21'
commands:
  nft:
    description: "Command to interact with the NFT marketplace"
    usage: "/nft <action>"